In [1]:
import torch
from einops import einsum,rearrange

In [5]:

X = torch.randn(3, 2, 3,1,2)
X

tensor([[[[[ 1.5536,  1.5832]],

          [[ 0.2697, -1.5186]],

          [[ 0.8133,  1.2879]]],


         [[[-1.7239, -0.0918]],

          [[ 0.3338, -0.2085]],

          [[-2.0095,  0.5221]]]],



        [[[[-0.1669,  1.3147]],

          [[-1.0036, -0.3147]],

          [[ 0.4353,  0.6237]]],


         [[[ 0.5371,  0.3050]],

          [[ 2.1390, -0.1724]],

          [[-1.8235, -2.0786]]]],



        [[[[-1.1545,  0.7307]],

          [[ 0.5173,  0.5538]],

          [[ 1.5493, -0.3973]]],


         [[[-0.9611, -0.0044]],

          [[ 0.9902, -0.7211]],

          [[-0.1170, -0.9117]]]]])

In [12]:
R = torch.randn(3,2,3,2,2)
R

tensor([[[[[ 0.5713,  1.0282],
           [ 0.6982, -1.1541]],

          [[ 0.8792,  0.2790],
           [ 0.9503,  0.3768]],

          [[ 0.8104, -1.1053],
           [-0.6793, -2.0892]]],


         [[[-0.3447, -1.1228],
           [-0.0131,  1.1091]],

          [[-1.7504,  0.3042],
           [ 0.2912, -0.2253]],

          [[-0.7090,  1.1476],
           [ 0.8632, -0.8096]]]],



        [[[[-2.5421, -0.6372],
           [-1.2401, -1.8393]],

          [[-1.1475, -0.3551],
           [-1.0730,  1.0320]],

          [[ 0.8372,  0.2571],
           [-1.5527, -0.4901]]],


         [[[-1.0632,  1.0088],
           [ 0.0080,  1.8577]],

          [[ 0.2154,  0.2595],
           [-1.3490,  1.1124]],

          [[-1.3731, -1.0520],
           [ 0.7171,  0.0145]]]],



        [[[[-0.4785, -0.3878],
           [-0.0234,  0.8686]],

          [[-1.6335,  1.0022],
           [-0.4498,  0.0683]],

          [[-0.7338,  0.9556],
           [-0.6267, -1.3075]]],


         [[[-0.1745,  0.41

In [ ]:
X_seq = X[0,0]
X_seq,X_seq.shape

tensor([[[ 1.5536,  1.5832]],

        [[ 0.2697, -1.5186]],

        [[ 0.8133,  1.2879]]])

In [19]:
R_seq = R[0,0]
R_seq,R_seq.shape

(tensor([[[ 0.5713,  1.0282],
          [ 0.6982, -1.1541]],
 
         [[ 0.8792,  0.2790],
          [ 0.9503,  0.3768]],
 
         [[ 0.8104, -1.1053],
          [-0.6793, -2.0892]]]),
 torch.Size([3, 2, 2]))

In [25]:
1.5536 * 0.5713 + 1.5832 * 1.0282

2.51541792

In [29]:
assert torch.allclose(einsum(X,R,"... seq x1 y, ... seq x y -> ... seq x1 x"),X @ rearrange(R,"... seq x y -> ... seq y x")) 

In [26]:
einsum(X_seq,R_seq,"... seq x1 y, ... seq x y -> ... seq x1 x")

tensor([[[ 2.5154, -0.7424]],

        [[-0.1865, -0.3159]],

        [[-0.7643, -3.2431]]])

In [23]:
X_seq @ rearrange(R_seq,"... seq x y -> ... seq y x")

tensor([[[ 2.5154, -0.7424]],

        [[-0.1865, -0.3159]],

        [[-0.7643, -3.2431]]])