In [10]:
import torch

In [11]:
X = torch.randn(4,5)
X

tensor([[-0.9868,  3.1611,  0.0414,  0.8184, -0.4409],
        [ 0.2849,  1.0272,  0.2919,  1.6290,  1.0371],
        [-1.3143, -1.3052,  0.8937, -1.1551, -1.5315],
        [ 0.3142, -0.4491, -0.4119, -0.6676, -3.1424]])

In [12]:
indices = torch.randint(low=0,high=5,size=(4,))
indices

tensor([0, 3, 0, 3])

In [15]:
torch.gather(X,dim=-1,index=indices.unsqueeze(-1)).squeeze(-1)

tensor([-0.9868,  1.6290, -1.3143, -0.6676])